### ISSUE TITLE
LoadError in Solargraph when globally installed

### ISSUE THREAD

**Issue by matthewtusker** [deepdivr/solargraph_test_coverage#2]
I'm trying to use `solargraph_test_coverage` in NeoVim, but I've installed solargraph globally (aka not in any Gemfiles) as I work in a few projects and want one setup that works for them all. I've managed to get everything working well, but when I added this Gem it started failing. When Solargraph is installed/configured in the project (aka not globally) then everything works fine). Here's the logs:

```
[START][2023-12-06 11:53:00] LSP logging initiated
[ERROR][2023-12-06 11:53:00] .../vim/lsp/rpc.lua:734	"rpc"	"/Users/username/.local/share/rtx/installs/ruby/3.1.2x64/bin/solargraph"	"stderr"	"Solargraph is listening on stdio PID=71888\n"
[ERROR][2023-12-06 11:53:01] .../vim/lsp/rpc.lua:734	"rpc"	"/Users/username/.local/share/rtx/installs/ruby/3.1.2x64/bin/solargraph"	"stderr"	"[WARN] LoadError when trying to require 'rails_helper'\n[WARN] [Gem::LoadError] You have already activated tilt 2.2.0, but your Gemfile requires tilt 2.0.10. Prepending `bundle exec` to your command may solve this.\n"
[ERROR][2023-12-06 11:53:01] .../vim/lsp/rpc.lua:734	"rpc"	"/Users/username/.local/share/rtx/installs/ruby/3.1.2x64/bin/solargraph"	"stderr"	"#<Thread:0x000000010ac9dbb8 /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host/message_worker.rb:43 run> terminated with exception (report_on_exception is true):\n"
[ERROR][2023-12-06 11:53:01] .../vim/lsp/rpc.lua:734	"rpc"	"/Users/username/.local/share/rtx/installs/ruby/3.1.2x64/bin/solargraph"	"stderr"	"<internal:/Users/username/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:38:in `require': cannot load such file -- kramdown (LoadError)\n"
[ERROR][2023-12-06 11:53:01] .../vim/lsp/rpc.lua:734	"rpc"	"/Users/username/.local/share/rtx/installs/ruby/3.1.2x64/bin/solargraph"	"stderr"	"\tfrom <internal:/Users/username/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:38:in `require'\n\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/pin/documenting.rb:3:in `<top (required)>'\n\tfrom <internal:/Users/username/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:38:in `require'\n\tfrom <internal:/Users/username/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:38:in `require'\n\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/pin/base.rb:10:in `<class:Base>'\n\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/pin/base.rb:7:in `<module:Pin>'\n\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/pin/base.rb:4:in `<module:Solargraph>'\n\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/pin/base.rb:3:in `<top (required)>'\n\tfrom <internal:/Users/username/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:38:in `require'\n\tfrom <internal:/Users/username/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:38:in `require'\n\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/pin/closure.rb:5:in `<module:Pin>'\n\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/pin/closure.rb:4:in `<module:Solargraph>'\n\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/pin/closure.rb:3:in `<top (required)>'\n\tfrom <internal:/Users/username/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:38:in `require'\n\tfrom <internal:/Users/username/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:38:in `require'\n\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/pin/namespace.rb:5:in `<module:Pin>'\n\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/pin/namespace.rb:4:in `<module:Solargraph>'\n\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/pin/namespace.rb:3:in `<top (required)>'\n\tfrom <internal:/Users/username/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:38:in `require'\n\tfrom <internal:/Users/username/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:38:in `require'\n\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/pin.rb:36:in `<module:Pin>'\n\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/pin.rb:8:in `<module:Solargraph>'\n\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/pin.rb:5:in `<top (required)>'\n\tfrom <internal:/Users/username/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:38:in `require'\n\tfrom <internal:/Users/username/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:38:in `require'\n\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/parser/region.rb:32:in `initialize'\n\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/parser/rubyvm/class_methods.rb:34:in `new'\n\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/parser/rubyvm/class_methods.rb:34:in `map'\n\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/source_map/mapper.rb:26:in `map'\n\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/source_map/mapper.rb:52:in `map'\n\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/source_map.rb:155:in `map'\n\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/library.rb:545:in `maybe_map'\n\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/library.rb:428:in `block in merge'\n\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/library.rb:426:in `synchronize'\n\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/library.rb:426:in `merge'\n"
[ERROR][2023-12-06 11:53:01] .../vim/lsp/rpc.lua:734	"rpc"	"/Users/username/.local/share/rtx/installs/ruby/3.1.2x64/bin/solargraph"	"stderr"	"\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host.rb:177:in `block in open'\n\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host.rb:176:in `each'\n\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host.rb:176:in `open'\n\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/language_server/message/text_document/did_open.rb:9:in `process'\n\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host.rb:112:in `receive'\n\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host/message_worker.rb:53:in `tick'\n\tfrom /Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host/message_worker.rb:44:in `block in start'\n"
```

The error itself seems to be coming from Solargraph, but only when this Gem is included. I've also made sure that `kramdown` is installed both globally _and_ in the Gemfile for the project I'm debugging in (as part of debugging). I'm a bit stumped, and I'd really love to get coverage reporting inline, so any help would be much appreciated.

**Comment by matthewtusker** [comment]
Looks like the issue can be solved by setting `preload_rails` to `false`. Never mind!
